### PR TITLE
Add run as administrator functionality

### PR DESCRIPTION
**Pull request by Zagrthos**
### Summary
This resolves an internal TODO inside the codebase to implement a proper working "Run as administrator" button dialog.

### Detailed Changes
The methods `IsRunningAdmin` and `RestartAsAdmin` are implemented inside the App.xaml.cs file. This was made because the old methods resided there and I just extended/replaced them.

The button dialogs in `GameGridPage.xaml.cs` were modified to use the newly introduced checks to work with. If a user chooses to run the app as admin it will be closed while a new one will be opened.

Also I added a new `Infobar` at the top of each page indicating if the app runs with administrative permissions.
image

### Notes
Additionally to the above changes I slightly modified the header layout of the Settings page to be more in line with how the other pages look.
This was necessary as otherwise the info bar would have looked absurdly crazy.
image

And while I was busy with that I also unified the XAML code of the `LibraryPage.xaml` file with how the other two look now.

### Edit
I also deleted the unused `BoolToVisibleConverter.cs` since inside the codebase only the CommunityToolkit approach is used.

### CODE REVIEW

**Comment by beeradmoore** [comment]
Adding for additional reference:
- #91, needing to run as admin was first discussed here, this is where that initial code you found came from
- #205, not directly related, but related to run as admin, if you launch DLSS Swapper directly from the installer it will run as admin as the installer runs as admin. I like the idea of the banners reflecting this.

Ideally running as admin isn't required, but if it is there and it works then that's great. So long as we don't nuke a users system accidentally 😬

I'll jump into the PR more on the weekend.

Those banners look great. Good job!

Good call for removing converter that isn't used.

Just a FYI, in the branch `feature/custom-directories` is where I am working on the manually add games feature. This will change the `GamesGrid` page, including the DLSS picker dropdown.  With the PRs you are doing I wanted to give you the heads up to not adjust that popup as it will be fully replaced and I wouldn't want you to waste your time on something that gets removed.

After review I'll bring your work into `main` and then `main` back into my branches and fix up any conflicts there.

**Comment by Zagrthos** [comment]
> So long as we don't nuke a users system accidentally

If only the directory where the game is gets modified I'm almost sure it wouldn't nuke the system - but I haven't implemented something that would remove System32 😄 

> This will change the GamesGrid page, including the DLSS picker dropdown.

I think besides changing the logic behind the two pages/controls (and adding the warning banners) I didn't touched them much.

Good heads-up tho with the info, I probably would've started getting rid of more issues which maybe involve the `GameGridPage`.

**Comment by beeradmoore** [comment]
Trying to test this and I am unsure if my test setup is correct. 

I went to my Cyberpunk 2077 folder and I changed the permissions so my PC user can't write to this folder, 

Screenshot 2024-08-25 145537

But an "administrators" can, 

Screenshot 2024-08-25 145528

My account is an administrator account, but I assume "administrators" is when you run something as admin. Trying to change a dll I get the prompt to relaunch as admin. After I relaunch I get the error of not being able to write to the target directory. From task manger I confirmed that the relaunched instance is running as elevated (which is the same as right mouse click > run as admin).

It may not be working as intended because the permissions I applied are not correct to replicate the problem we are trying to solve.

I am downloading The Ascent from the Windows Store as it is what I had a problem with before, but I am pretty sure it is installing with the same mechanism as the Xbox app does which would be a valid install.

Do you have any recomendations on how to test this?



Aside from that the only other thing I am not 100% sure on is the text in the admin banner. I don't like how it says "Administrative Privileges" twice so close to each other. I tried changing the title to "Warning", its better, but it still isn't great. Mabye just not having a title at all? Any thoughts on that?

image

I was also thinking about if we needed a "disable running as administrator banners" in settings but I think the value it adds is tiny compared to starting to clutter the settings page it would do for every other user. So probably not.

**Comment by Zagrthos** [comment]
> I was also thinking about if we needed a "disable running as administrator banners" in settings but I think the value it adds is tiny compared to starting to clutter the settings page it would do for every other user. So probably not.

We can flip the `IsClosable` switch. Then users are able to click on the "X" and it vanishes. My initial intent was to "force" showing this as administrative privileges are somewhat dangerous.

> Aside from that the only other thing I am not 100% sure on is the text in the admin banner. I don't like how it says "Administrative Privileges" twice so close to each other. I tried changing the title to "Warning", its better, but it still isn't great. Mabye just not having a title at all? Any thoughts on that?

Changed this bugged me in the end too but I wanted to wait for feedback. 😄

> My account is an administrator account, but I assume "administrators" is when you run something as admin.

`Administrators` is actually the built-in windows group, same as for `Users`. But I tested this right now with a clean `User` (no additional perms and denied writing perms on a Steam folder). I get the same error now. Currently investigating.

**Comment by Zagrthos** [comment]
Okay I got to a point.
If you have denied writing perms on the `Users` group you are unable to test this without an explicit account which is only inside the `Administrators` group. Your default user account (which is created after the successful installation of windows) is in both groups (`Users` and `Administrators`). And because the denial of a permission weights higher than granting a perm you are unable to do that.

**Comment by beeradmoore** [comment]
> We can flip the IsClosable switch. Then users are able to click on the "X" and it vanishes. My initial intent was to "force" showing this as administrative privileges are somewhat dangerous.

I was thinking to disable it completely and never show again. I think lets keep it as is without the "X" and if people don't like it (realistically most people will never see it) we can look at what would be the best way to handle it then.

I'll try get to re-test this by the weekend, but if not it will be on the weekend.

**Comment by beeradmoore** [comment]
I did not get time this weekend, I will try ASAP though

**Comment by beeradmoore** [comment]
> Edit 2: I got a test case now and verified it's working correctly.

The extra thing I had to do here was remove the permissions for `Authenticated Users`. I was able to test, see the failure, relauch, and then successfully change DLSS. 

Thanks for your work on this one.

**Pull request merged**
